# Generated by Django 3.2.7 on 2022-05-16 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('category', models.CharField(default='', max_length=100)),
                ('scientific_name', models.CharField(default='', max_length=100)),
                ('breading_time', models.CharField(default='', max_length=100)),
                ('age', models.CharField(default='', max_length=100)),
                ('food', models.CharField(default='', max_length=100)),
                ('vaccination', models.CharField(default='', max_length=100)),
                ('medical_history', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('date', models.CharField(default='', max_length=100)),
                ('time', models.CharField(default='', max_length=100)),
                ('age_cat', models.CharField(default='', max_length=100)),
                ('price', models.CharField(default='', max_length=100)),
                ('ticket_no', models.IntegerField(default='')),
                ('status', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=100)),
                ('pswd', models.CharField(default='', max_length=100)),
                ('utype', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('pswd', models.CharField(default='', max_length=100)),
                ('utype', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('report', models.CharField(default='', max_length=100)),
                ('date', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('staff_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='zooapp.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.CharField(default='', max_length=100)),
                ('date', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('doctor_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='zooapp.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_needs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needs', models.CharField(default='', max_length=100)),
                ('food_qty', models.CharField(default='', max_length=100)),
                ('date', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('staff_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='zooapp.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(default='', max_length=100)),
                ('date', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('user_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='zooapp.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(default='', max_length=100)),
                ('food_qty', models.CharField(default='', max_length=100)),
                ('price', models.CharField(default='', max_length=100)),
                ('date', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('supplier_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='zooapp.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_appoinment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_email', models.CharField(default='', max_length=100)),
                ('date', models.CharField(default='', max_length=100)),
                ('time', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('animal_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='zooapp.tbl_animal')),
                ('doctor_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='zooapp.tbl_user')),
            ],
        ),
    ]
