# Generated by Django 3.2.7 on 2022-05-16 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zooapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tbl_appoinment',
        ),
    ]
