# Generated by Django 3.2.7 on 2022-05-16 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zooapp', '0002_delete_tbl_appoinment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_appoinment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_email', models.CharField(default='', max_length=100)),
                ('date', models.CharField(default='', max_length=100)),
                ('time', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('animal_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='zooapp.tbl_animal')),
                ('doctor_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='zooapp.tbl_user')),
            ],
        ),
    ]
