# Generated by Django 3.2.7 on 2022-05-16 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zooapp', '0003_tbl_appoinment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tbl_food',
            new_name='Tbl_foodsupply',
        ),
    ]
