# Generated by Django 3.2.7 on 2022-05-18 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zooapp', '0004_rename_tbl_food_tbl_foodsupply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_foodstock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(default='', max_length=100)),
                ('food_qty', models.CharField(default='', max_length=100)),
                ('stock', models.CharField(default='', max_length=100)),
                ('date', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('staff_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='zooapp.tbl_user')),
            ],
        ),
    ]
