# Generated by Django 3.2.7 on 2022-05-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zooapp', '0005_tbl_foodstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_foodstock',
            name='food_category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tbl_foodsupply',
            name='food_category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
