# Generated by Django 3.2.7 on 2022-05-18 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zooapp', '0006_auto_20220518_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_needs',
            name='food_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='zooapp.tbl_foodstock'),
        ),
    ]
