# Generated by Django 3.2.7 on 2022-05-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zooapp', '0007_tbl_needs_food_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_user',
            old_name='address',
            new_name='city',
        ),
        migrations.AddField(
            model_name='tbl_user',
            name='pin',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tbl_user',
            name='street',
            field=models.CharField(default='', max_length=100),
        ),
    ]
