# Generated by Django 3.2.7 on 2022-05-19 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zooapp', '0008_auto_20220519_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_name', models.CharField(default='', max_length=100)),
                ('v_date', models.CharField(default='', max_length=100)),
                ('discription', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('animal_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='zooapp.tbl_animal')),
                ('staff_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='zooapp.tbl_user')),
            ],
        ),
    ]
