# Generated by Django 3.2.7 on 2022-05-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zooapp', '0009_tbl_vaccine'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_booking',
            name='count',
            field=models.CharField(default='', max_length=100),
        ),
    ]
