# Generated by Django 4.0.4 on 2022-06-15 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zooapp', '0010_tbl_booking_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_animal',
            old_name='breading_time',
            new_name='life_span',
        ),
    ]
