# Generated by Django 3.2.7 on 2022-06-29 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zooapp', '0011_rename_breading_time_tbl_animal_life_span'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(default='', max_length=100)),
                ('book_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='zooapp.tbl_booking')),
            ],
        ),
    ]
